# Что сегодня сделаем
Рекомендательный алгоритм сопутствующих товаров для пользователя

### Повторим списки и словари
Статистика взята с сайта http://www.bodycounters.com

Дана статистика погибших в серии фильмов "Пираты Карибского моря". Посчитайте среднее число погибших людей в каждом фильме. Пиратов зомби за людей не считайте.

In [1]:
stats = [
    {
        'movie': 'На странных берегах',
        'bodycount': {'люди': 56, 'русалки': 2, 'ядовитые жабы': 3, 'пираты-зомби': 2}
    },
    {
        'movie': 'На краю света',
        'bodycount': {'люди': 88}
    },
    {
        'movie': 'Сундук мертвеца',
        'bodycount': {'люди': 56, 'крабы отшельники': 1}
    },
    {
        'movie': 'Проклятие Черной жемчужины',
        'bodycount': {'люди': 17}
    },
]

Что можно сделать:
1. Пройтись по списку stats
2. В каждом элементе взять словарь по ключу 'bodycount'
3. В словаре по ключу 'bodycount' взять значение ключа 'люди'
4. Просуммировать количество людей во всех шагах
5. Поделить сумму людей на количество фильмов

In [11]:
sum = 0
for i in stats:
    sum += i['bodycount']['люди']
sum//len(stats)

54

In [2]:
sum([el['bodycount']['люди'] for el in stats ])/ len(stats)

54.25

# Numpy и матричная алгебра

In [3]:
import numpy as np

In [13]:
x = np.array([1, 2, 3])
y = np.array( [4, 5, 6] )

In [14]:
# у переменной x тип, отличный от list
type(x)

numpy.ndarray

In [15]:
# дополнительные методы
x.mean()

2.0

### Поэлементные операции

In [16]:
x + y

array([5, 7, 9])

In [17]:
x - y

array([-3, -3, -3])

In [18]:
x * y

array([ 4, 10, 18])

In [19]:
x / y

array([0.25, 0.4 , 0.5 ])

In [20]:
# элементы массива x возводятся в соответствующие степени элементов массива y
x ** y

array([  1,  32, 729])

In [21]:
# остаток от деления
# обратите внимание, что для удобства данного примера x и y идут в другом порядке

y % x

array([0, 1, 0])

### Автоматическое наполнение массивов

In [22]:
# аналог range

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# создать массив из 10 чисел, заполненных единицами
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
# создать матрицу 2х5 из нулей
np.full([2, 5], 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
# объединить массивы в один
a = np.arange(10)
b = np.arange(10, 20)

# обратите внимание на двойные скобки
np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
# перемешать элементы массива
import random

nums = np.arange(10)
random.shuffle(nums)

nums

array([1, 4, 9, 3, 0, 7, 5, 8, 2, 6])

### Упражнение
По мотивам https://thecode.media/choose-life/

По результатам собеседования вам предлагают определенную зарплату. И конверт, который может случайным образом снизить или увеличить эту зарплату вдвое. Т. е. если сначала была сумма Х, то после вскрытия конверта она может стать 0.5Х или 2Х. Как в среднем изменится будущая зарплата, если соискатель решил открыть конверт?

Смоделируйте процесс изменения условной зарплаты в 1000 в случае открытия конверта:
1. Задайте переменную n_samples = 1000
2. Создайте numpy array из n_samples элементов, равных зарплате 0.5Х. И такой же с зарплатой 2Х.
3. Объедините их в один массив
4. Перемешайте значения в получившемся массиве
5. Посчитайте среднее значение зарплаты для объединенного массива

In [27]:
n_samples = 1000
pay = 100000

In [ ]:
np.full(
  shape=10,
  fill_value=3,
  dtype=np.int
)

In [30]:
arr=np.ones(n_samples)*(pay/2)
arr

array([50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
       50000., 50000., 50000., 50000., 50000., 50000., 50000., 50000.,
      

In [31]:
arr1=np.ones(n_samples)*pay*2
arr1

array([200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 200000., 200000., 200000., 200000., 200000., 200000.,
       200000., 2000

In [46]:
type(arr[0]), type(arr), arr.size

(numpy.float64, numpy.ndarray, 1000)

In [4]:
import random

In [49]:
conc_arr = np.concatenate((arr,arr1))
random.shuffle(conc_arr)

In [51]:
type(sum_arr),conc_arr

(NoneType, array([ 50000., 200000.,  50000., ...,  50000., 200000., 200000.]))

In [53]:
np.sum(conc_arr)/conc_arr.size

125000.0

In [5]:
n_samples = 1000
half = np.full(n_samples, 0.5)
twin = np.full(n_samples, 2)
rs = np.concatenate((half,twin))
random.shuffle(rs)
rs.mean()

1.25

### Изменение размерности

In [2]:
x = np.arange( 0, 10 )
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 10 - количество строк

x.shape

(10,)

In [4]:
# первый аргумент - количество строк
# второй - столбцов

x.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
x.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [6]:
# транспонирование матриц

np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
).T

array([[1, 3, 5],
       [2, 4, 6]])

In [7]:
# склеивание набора списков
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [8]:
# склеивание массива из списков

x = np.array( [ [1, 2, 3], [4, 5, 6] ] )
x.ravel()

array([1, 2, 3, 4, 5, 6])

In [9]:
# можно и так

x.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# результат разный, если добавить 1 в качестве количества строк

x.reshape(1, 6)

### Создание матриц

In [ ]:
# нулевой вектор заданной размерности

np.zeros(10)

In [ ]:
# единичная матрица

np.eye(5)

In [ ]:
# более общий случай диагональной матрицы

np.diag(np.arange(2, 50, 15), k=0)

In [ ]:
# матрица со случайными значениями

np.random.random(10)

In [ ]:
# более универсальный вариант создания матриц

?np.linspace

In [ ]:
np.linspace(5, 25, 30)

### Более сложные распределения

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.gaussian.html

### Упражнение
Дана единичная матрица np.eye(10). Посчитайте сумму ее диагональных элементов.

# Скалярное произведение векторов

\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = |\vec{a}| \space |\vec{b}| \space cos(\vec{a}, \vec{b})
\end{equation*}

Пусть 
\begin{equation*}
\LARGE
\vec{a} = (a_1, a_2, a_3) \\
\LARGE
\vec{b} = (b_1, b_2, b_3)
\end{equation*}

Тогда скалярное произведение векторов равно
\begin{equation*}
\LARGE
\vec{a} \dot{} \vec{b} = a_1 b_1 + a_2 b_2 + a_3 b_3
\end{equation*}

In [ ]:
a = np.array( [4, 3] )
b = np.array( [2, 1] )

Пример расчета скалярного произведения векторов

In [ ]:
np.dot( a, b )

Можно посчитать и таким образом

In [ ]:
# первый шаг

for pair in zip( a, b ):
    print( pair )

In [ ]:
# второй шаг

[ pair[0] * pair[1] for pair in zip( a, b ) ]

In [ ]:
# итоговый результат

sum( [ pair[0] * pair[1] for pair in zip( a, b ) ] )

# Косинусное расстояние между векторами

\begin{equation*}
\LARGE
cos(\vec{a}, \vec{b}) = \frac{\vec{a} \dot{} \vec{b}}{|\vec{a}| \space |\vec{b}|}
\end{equation*}

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
ax = plt.axes()

plt.xlim( [0, 5] )
plt.ylim( [0, 4] )

ax.arrow( 0, 0, a[0], a[1], head_width=0.1, head_length=0.2, fc='k', ec='k' )
ax.arrow( 0, 0, b[0], b[1], head_width=0.1, head_length=0.2, fc='k', ec='k' )

plt.show()

In [ ]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [ ]:
# длины векторов можно было посчитать и так

aLength = np.sqrt( (a*a).sum() )
bLength = np.sqrt( (b*b).sum() )

In [ ]:
cosine( a, b )

In [ ]:
# угол между векторами в радианах

np.arccos( cosine( a, b ) )

In [ ]:
# угол между векторами в градусах

np.arccos( cosine( a, b ) ) * 360 / 2 / np.pi

## Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

# Перемножение матриц

**Определение**

Пусть даны две матрицы a и b размером l x m и m x n соответственно. l - количество строк, n - количество столбцов.

\begin{equation*}
\LARGE
a = 
\begin{bmatrix}
    a_{11} & a_{12} \dots a_{1m} \\
    a_{21} & a_{22} \dots a_{2m} \\
    \vdots & \vdots \dots \vdots \\
    a_{l1} & a_{l2} \dots a_{lm}
\end{bmatrix}
\end{equation*}

<br>

\begin{equation*}
\LARGE
b = 
\begin{bmatrix}
    b_{11} & b_{12} \dots b_{1n} \\
    b_{21} & b_{22} \dots b_{2n} \\
    \vdots & \vdots \dots \vdots \\
    b_{m1} & b_{m2} \dots b_{mn}
\end{bmatrix}
\end{equation*}

Тогда произведением матриц a и b будет матрица c размерностью l x n:

\begin{equation*}
\LARGE
c = 
\begin{bmatrix}
    c_{11} & c_{12} \dots c_{1n} \\
    c_{21} & c_{22} \dots c_{2n} \\
    \vdots & \vdots \dots \vdots \\
    c_{l1} & c_{l2} \dots c_{ln}
\end{bmatrix}
\end{equation*}

<br>

\begin{equation*}
\LARGE
c_{ij} = \sum_{k=1}^m a_{ik} b_{kj}
\end{equation*}

<img src = 'https://wikimedia.org/api/rest_v1/media/math/render/svg/1f96c71f0a99eac3ee872e7baf22e84324d7b4c9' style="width: 80%"></img>

In [ ]:
a = np.array( 
    [
        [1, 2],
        [3, 4]
    ] 
)

In [ ]:
b = np.array( 
    [
        [5, 6],
        [7, 8]
    ] 
)

In [ ]:
c = np.dot( a, b )
c

В numpy есть специальный тип matrix, который отличается от ndarray

In [ ]:
aMatrix = np.matrix( [ [1, 2], [3, 4] ] )
bMatrix = np.matrix( [ [5, 6], [7, 8] ] )

In [ ]:
type(aMatrix)

In [ ]:
aMatrix * bMatrix

In [ ]:
type( aMatrix ), type( a )

In [ ]:
np.mat( a ) * np.mat( b )

# Линейные уравнения

Дана система линейных уравнений

\begin{equation*}
\LARGE
x + 3*y = 9 \\
\LARGE
2*x - 4*y = 8
\end{equation*}

In [ ]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [1, 3], [2, -4] ] )

In [ ]:
# значения в правой части уравнения

b = np.array( [9, 8] )

In [ ]:
# решение

from numpy import linalg

In [ ]:
linalg.solve(a, b)

In [ ]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )